---

- name: Deploy the bastion
  hosts: bastion
  user: ansible
  become: True
  become_user: root

  roles:
    - { role: ubuntu,
        hostname: "bastion"}
    - { role: bastion,
        apt_packages: ["git",
                       "python-dev",
                       "python",
                       "pip",
                       "python-virtualenv",
                       "sshpass"]
      }
