---

- name: Deploy the production buildmaster
  hosts: prodmaster
  remote_user: ubuntu 
  become: yes
  become_method: sudo

  roles: 
    - ubuntu
    - { role: buildmaster,
        hostname: "PRODbuildmaster"}
