---

- name: Deploy the production buildmaster
  hosts: prodmaster
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - { role: ubuntu,
        hostname: "PRODbuildmaster"}
    - buildmaster
