---
- name: Load SSH keys from public_keys.yml
  include_vars: public_keys.yml
- name: Create users group
  group:
    name=users
    state=present
- name: Create user acrichto
  user: 
    name=acrichto
    shell=/bin/bash
    groups=users
- name: Authorize acrichto's ssh keys from GitHub
  authorized_key:
    user=acrichto
    key=https://github.com/alexcrichton.keys
    state=present
- name: Create user edunham
  user: 
    name=edunham
    shell=/bin/bash
    groups=users
- name: Authorize edunham's ssh key
  authorized_key:
    user=edunham
    key="{{ edunham_pubkey }}"
    state=present
