---
language: python
python: "2.7"
sudo: false

install:
    - pip install ansible
    - pip install ansible-lint
    - ansible-galaxy install -r galaxy_roles.yaml

script:
    - "ansible-lint -i tests/inventory provision/bastion.yaml"
    - "ansible-lint -i tests/inventory provision/buildmaster.yaml"
    - "ansible-lint -i tests/inventory provision/proxy.yaml"
    - "ansible-lint -i tests/inventory provision/playground.yaml"
