---
# This playbook applies all roles to their respective hosts

- name: Apply ability to clone from Github
  hosts: all
  roles:
    - common

- name: Deploy the bastion
  hosts: bastion
  roles: 
    - bastion

- name: Deploy the proxy
  hosts: proxy
  roles: 
    - proxy

- name: Deploy the playground
  hosts: play 
  roles: 
    - playground

- name: Deploy the buildmaster
  hosts: buildmaster
  roles: 
    - buildmaster

- name: Deploy the buildslaves
  hosts: buildslave
  roles: 
    - buildslave
