---
- name: Set hostname
  hostname:
      name=proxy

- name: Install or update nginx and openssl
  apt:
      pkg={{ item }}
      state=latest
      update_cache=yes
  with_items:
      - nginx
      - openssl

- name: Create /etc/nginx/ssl directory
  file:
      path=/etc/nginx/ssl
      state=directory
      owner={{ ansible_ssh_user }}
      group={{ ansible_ssh_user }}

- name: Create a 2048-bit dhparams.pem key if it doesn't exist
  command: openssl dhparam -out dhparams.pem 2048
  args:
      chdir: /etc/nginx/ssl
      creates: /etc/nginx/ssl/dhparams.pem

- name: Create a SSL cert if it doesn't exist
  command: >
         openssl req
         -new
         -nodes
         -x509
         -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=doc.rust-lang.org"
         -days 3650
         -keyout /etc/nginx/ssl/server.key
  args:
      creates: /etc/nginx/ssl/nginx.key
      creates: /etc/nginx/ssl/nginx.crt

- name: Copy enabled sites
  copy:
      src=sites-enabled/{{ item }}
      dest=/etc/nginx/sites-enabled/{{ item }}
  with_items: enabled_sites

- name: Copy nginx config files
  copy:
      src=conf.d/{{ item }}
      dest=/etc/nginx/conf.d/{{ item }}
  with_items: nginx_config_files

- name: Start nginx service
  service:
      name=nginx
      state=reloaded
