---
- name: Download Python pkg
  get_url:
    url="https://www.python.org/ftp/python/2.7.11/python-2.7.11-macosx10.6.pkg"
    dest="/Users/administrator/python.pkg"
  when: install_python == True

- name: Install latest Python
  command: installer -pkg python.pkg -target /
  args:
    creates: /usr/local/bin/python
  become: yes
  when: install_python == True

- name: Link Python stuff to default path
  file:
    src="/Library/Frameworks/Python.framework/Versions/2.7/bin/{{item}}"
    dest="/usr/local/bin/{{item}}"
    state=link
  with_items:
    - pip
    - virtualenv
  when: install_python == True

- name: check for buildslave venv
  stat:
   path=/Users/administrator/buildslave-venv
  register: buildslave_venv

- name: Create buildslave venv
  command: /usr/local/bin/virtualenv /Users/administrator/buildslave-venv
  when: buildslave_venv.stat.exists == False

- name: Upgrade pip
  pip:
    name=pip
    extra_args="--upgrade"
    virtualenv="/Users/administrator/buildslave-venv"

- name: Install buildbot-slave to venv
  pip:
    name=buildbot-slave
    virtualenv="/Users/administrator/buildslave-venv"

- name: Clone the Buildbot configs
  git:
      repo='https://github.com/rust-lang/rust-buildbot.git'
      dest='/Users/administrator/rust-buildbot'
      version=master
      accept_hostkey=yes
      force=yes

- name: Pretend to have run setup-slave.sh, place stunnel conf
  copy:
    src=rust-buildbot-slave-stunnel-final.conf
    dest="{{stunnel_conf_path}}/rust-buildbot-slave-stunnel-final.conf"

- name: setup-slave, Start stunnel
  command: "/usr/local/bin/stunnel rust-buildbot-slave-stunnel-final.conf"
  args:
    chdir: "{{ stunnel_conf_path }}"
  ignore_errors: yes

- name: setup-slave, Nuke old artifacts
  file:
    path=/Users/administrator/rust-buildbot/slave
    state=absent

# buildslave create-slave BASEDIR MASTERHOST:PORT SLAVENAME PASSWORD
- name: setup-slave, (re)create buildbot slave
  command: "/Users/administrator/buildslave-venv/bin/buildslave create-slave
--force /Users/administrator/rust-buildbot/slave localhost:9987 {{ slavename }} {{ buildslave_password }}"
  become: yes
  become_method: sudo

- name: Clear admin email boilerplate
  lineinfile:
    dest=/Users/administrator/rust-buildbot/slave/info/admin
    line='Your Name Here <admin@youraddress.invalid>'
    state=absent

- name: Clear slave description boilerplate
  lineinfile:
    dest=/Users/administrator/rust-buildbot/slave/info/admin
    line='Please put a description of this build host here'
    state=absent

- name: set admin email
  lineinfile:
    dest=/Users/administrator/rust-buildbot/slave/info/admin
    line='admin@rust-lang.org'
    insertafter=EOF

- name: Start or restart buildslave
  command: /Users/administrator/buildslave-venv/bin/buildslave restart slave
  args:
    chdir: /Users/administrator/rust-buildbot

- name: set hostname
  lineinfile:
    dest=/Users/administrator/rust-buildbot/slave/info/host
    line="{{inventory_hostname}}"
    insertafter=EOF

- name: Set up firewall rules to only allow ssh from bastion
  copy:
    src=pf.conf
    dest=/etc/pf.conf
  become: yes
  register: pfconf

- name: enable firewall
  command: pfctl -e
  become: yes
  when: pfconf.changed

- name: flush firewall rules (this kills the connection)
  command: pfctl -Fa -f /etc/pf.conf
  become: yes
  when: pfconf.changed
