---

- name: Install Required Packages
  homebrew:
    - name={{ item}}
    - state=present
    - update_homebrew=yes
    - upgrade_all=yes
  with_items: 
    - python
    - pip
    - git

- name: Install virtualenv
  pip:
    - name='virtualenv'

- name: Create Rustbuild user
  user:
    - name='rustbuild'
    - createhome=yes
    - state=present

- name: Clone the Buildbot configs
  git:
      repo='https://github.com/rust-lang/rust-buildbot.git'
      dest='/home/rustbuild/rust-buildbot'
      accept_hostkey=yes
  become: yes
  become_user: rustbuild

- name: Create venv for buildslave
  pip: 
    - virtualenv={{venv_path}}
    - name='buildbot'
# TODO: open ports for buildslave
