---
- name: Set hostname
  hostname: 
      name={{ hostname }}

- name: Install prerequisite packages
  apt:
      pkg={{ item }}
      state=present
  with_items:
      - python
      - python-pip
      - python-dev
      - python-setuptools
      - stunnel
      - git

- name: install Buildbot
  easy_install:
      name: buildbot==0.8.12

- name: Create buildbot user
  user:
      name: "rustbuild"
      home: "/home/rustbuild"
      shell: /bin/bash
      createhome: yes

- name: Clone the Buildbot configs
  git:
      repo='https://github.com/rust-lang/rust-buildbot.git'
      dest='/home/buildbot/rust-buildbot'
      accept_hostkey=yes

- name: Start Buildbot
  command: buildbot start master
  args:
      chdir: /home/rustbuild/rust-buildbot
  become: yes
  become_user: rustbuild 
